version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personal_library
    ports:
      - '5432:5423'