name: CI

on:
  push:
    branches: [ main ]

  #pull_request:
  #  branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & Up app
        run: docker-compose up --build -d

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Reset db Postgres
        run: docker-compose run app rails db:reset

      - name: Run tests
        run: docker-compose run app rspec

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run lint
        run: docker-compose run app bash -c "gem install rubocop; rubocop -A --fail-level F"